// Package toto contains the types for schema 'jlabo'.
package toto

// Code generated by xo. DO NOT EDIT.

import (
	"errors"
)

// WsubFinderLinksTermsb represents a row from 'jlabo.wsub_finder_links_termsb'.
type WsubFinderLinksTermsb struct {
	LinkID uint    `json:"link_id"` // link_id
	TermID uint    `json:"term_id"` // term_id
	Weight float32 `json:"weight"`  // weight

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the WsubFinderLinksTermsb exists in the database.
func (wflt *WsubFinderLinksTermsb) Exists() bool {
	return wflt._exists
}

// Deleted provides information if the WsubFinderLinksTermsb has been deleted from the database.
func (wflt *WsubFinderLinksTermsb) Deleted() bool {
	return wflt._deleted
}

// Insert inserts the WsubFinderLinksTermsb to the database.
func (wflt *WsubFinderLinksTermsb) Insert(db XODB) error {
	var err error

	// if already exist, bail
	if wflt._exists {
		return errors.New("insert failed: already exists")
	}

	// sql insert query, primary key must be provided
	const sqlstr = `INSERT INTO jlabo.wsub_finder_links_termsb (` +
		`link_id, term_id, weight` +
		`) VALUES (` +
		`?, ?, ?` +
		`)`

	// run query
	XOLog(sqlstr, wflt.LinkID, wflt.TermID, wflt.Weight)
	_, err = db.Exec(sqlstr, wflt.LinkID, wflt.TermID, wflt.Weight)
	if err != nil {
		return err
	}

	// set existence
	wflt._exists = true

	return nil
}

// Update updates the WsubFinderLinksTermsb in the database.
func (wflt *WsubFinderLinksTermsb) Update(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !wflt._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if wflt._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query with composite primary key
	const sqlstr = `UPDATE jlabo.wsub_finder_links_termsb SET ` +
		`weight = ?` +
		` WHERE link_id = ? AND term_id = ?`

	// run query
	XOLog(sqlstr, wflt.Weight, wflt.LinkID, wflt.TermID)
	_, err = db.Exec(sqlstr, wflt.Weight, wflt.LinkID, wflt.TermID)
	return err
}

// Save saves the WsubFinderLinksTermsb to the database.
func (wflt *WsubFinderLinksTermsb) Save(db XODB) error {
	if wflt.Exists() {
		return wflt.Update(db)
	}

	return wflt.Insert(db)
}

// Delete deletes the WsubFinderLinksTermsb from the database.
func (wflt *WsubFinderLinksTermsb) Delete(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !wflt._exists {
		return nil
	}

	// if deleted, bail
	if wflt._deleted {
		return nil
	}

	// sql query with composite primary key
	const sqlstr = `DELETE FROM jlabo.wsub_finder_links_termsb WHERE link_id = ? AND term_id = ?`

	// run query
	XOLog(sqlstr, wflt.LinkID, wflt.TermID)
	_, err = db.Exec(sqlstr, wflt.LinkID, wflt.TermID)
	if err != nil {
		return err
	}

	// set deleted
	wflt._deleted = true

	return nil
}

// WsubFinderLinksTermsbsByLinkIDTermIDWeight retrieves a row from 'jlabo.wsub_finder_links_termsb' as a WsubFinderLinksTermsb.
//
// Generated from index 'idx_link_term_weight'.
func WsubFinderLinksTermsbsByLinkIDTermIDWeight(db XODB, linkID uint, termID uint, weight float32) ([]*WsubFinderLinksTermsb, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`link_id, term_id, weight ` +
		`FROM jlabo.wsub_finder_links_termsb ` +
		`WHERE link_id = ? AND term_id = ? AND weight = ?`

	// run query
	XOLog(sqlstr, linkID, termID, weight)
	q, err := db.Query(sqlstr, linkID, termID, weight)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*WsubFinderLinksTermsb{}
	for q.Next() {
		wflt := WsubFinderLinksTermsb{
			_exists: true,
		}

		// scan
		err = q.Scan(&wflt.LinkID, &wflt.TermID, &wflt.Weight)
		if err != nil {
			return nil, err
		}

		res = append(res, &wflt)
	}

	return res, nil
}

// WsubFinderLinksTermsbsByTermIDWeight retrieves a row from 'jlabo.wsub_finder_links_termsb' as a WsubFinderLinksTermsb.
//
// Generated from index 'idx_term_weight'.
func WsubFinderLinksTermsbsByTermIDWeight(db XODB, termID uint, weight float32) ([]*WsubFinderLinksTermsb, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`link_id, term_id, weight ` +
		`FROM jlabo.wsub_finder_links_termsb ` +
		`WHERE term_id = ? AND weight = ?`

	// run query
	XOLog(sqlstr, termID, weight)
	q, err := db.Query(sqlstr, termID, weight)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*WsubFinderLinksTermsb{}
	for q.Next() {
		wflt := WsubFinderLinksTermsb{
			_exists: true,
		}

		// scan
		err = q.Scan(&wflt.LinkID, &wflt.TermID, &wflt.Weight)
		if err != nil {
			return nil, err
		}

		res = append(res, &wflt)
	}

	return res, nil
}

// WsubFinderLinksTermsbByTermID retrieves a row from 'jlabo.wsub_finder_links_termsb' as a WsubFinderLinksTermsb.
//
// Generated from index 'wsub_finder_links_termsb_term_id_pkey'.
func WsubFinderLinksTermsbByTermID(db XODB, termID uint) (*WsubFinderLinksTermsb, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`link_id, term_id, weight ` +
		`FROM jlabo.wsub_finder_links_termsb ` +
		`WHERE term_id = ?`

	// run query
	XOLog(sqlstr, termID)
	wflt := WsubFinderLinksTermsb{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, termID).Scan(&wflt.LinkID, &wflt.TermID, &wflt.Weight)
	if err != nil {
		return nil, err
	}

	return &wflt, nil
}
