// Package toto contains the types for schema 'jlabo'.
package toto

// Code generated by xo. DO NOT EDIT.

import (
	"errors"
)

// WsubFinderLinksTerms3 represents a row from 'jlabo.wsub_finder_links_terms3'.
type WsubFinderLinksTerms3 struct {
	LinkID uint    `json:"link_id"` // link_id
	TermID uint    `json:"term_id"` // term_id
	Weight float32 `json:"weight"`  // weight

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the WsubFinderLinksTerms3 exists in the database.
func (wflt *WsubFinderLinksTerms3) Exists() bool {
	return wflt._exists
}

// Deleted provides information if the WsubFinderLinksTerms3 has been deleted from the database.
func (wflt *WsubFinderLinksTerms3) Deleted() bool {
	return wflt._deleted
}

// Insert inserts the WsubFinderLinksTerms3 to the database.
func (wflt *WsubFinderLinksTerms3) Insert(db XODB) error {
	var err error

	// if already exist, bail
	if wflt._exists {
		return errors.New("insert failed: already exists")
	}

	// sql insert query, primary key must be provided
	const sqlstr = `INSERT INTO jlabo.wsub_finder_links_terms3 (` +
		`link_id, term_id, weight` +
		`) VALUES (` +
		`?, ?, ?` +
		`)`

	// run query
	XOLog(sqlstr, wflt.LinkID, wflt.TermID, wflt.Weight)
	_, err = db.Exec(sqlstr, wflt.LinkID, wflt.TermID, wflt.Weight)
	if err != nil {
		return err
	}

	// set existence
	wflt._exists = true

	return nil
}

// Update updates the WsubFinderLinksTerms3 in the database.
func (wflt *WsubFinderLinksTerms3) Update(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !wflt._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if wflt._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query with composite primary key
	const sqlstr = `UPDATE jlabo.wsub_finder_links_terms3 SET ` +
		`weight = ?` +
		` WHERE link_id = ? AND term_id = ?`

	// run query
	XOLog(sqlstr, wflt.Weight, wflt.LinkID, wflt.TermID)
	_, err = db.Exec(sqlstr, wflt.Weight, wflt.LinkID, wflt.TermID)
	return err
}

// Save saves the WsubFinderLinksTerms3 to the database.
func (wflt *WsubFinderLinksTerms3) Save(db XODB) error {
	if wflt.Exists() {
		return wflt.Update(db)
	}

	return wflt.Insert(db)
}

// Delete deletes the WsubFinderLinksTerms3 from the database.
func (wflt *WsubFinderLinksTerms3) Delete(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !wflt._exists {
		return nil
	}

	// if deleted, bail
	if wflt._deleted {
		return nil
	}

	// sql query with composite primary key
	const sqlstr = `DELETE FROM jlabo.wsub_finder_links_terms3 WHERE link_id = ? AND term_id = ?`

	// run query
	XOLog(sqlstr, wflt.LinkID, wflt.TermID)
	_, err = db.Exec(sqlstr, wflt.LinkID, wflt.TermID)
	if err != nil {
		return err
	}

	// set deleted
	wflt._deleted = true

	return nil
}

// WsubFinderLinksTerms3sByLinkIDTermIDWeight retrieves a row from 'jlabo.wsub_finder_links_terms3' as a WsubFinderLinksTerms3.
//
// Generated from index 'idx_link_term_weight'.
func WsubFinderLinksTerms3sByLinkIDTermIDWeight(db XODB, linkID uint, termID uint, weight float32) ([]*WsubFinderLinksTerms3, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`link_id, term_id, weight ` +
		`FROM jlabo.wsub_finder_links_terms3 ` +
		`WHERE link_id = ? AND term_id = ? AND weight = ?`

	// run query
	XOLog(sqlstr, linkID, termID, weight)
	q, err := db.Query(sqlstr, linkID, termID, weight)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*WsubFinderLinksTerms3{}
	for q.Next() {
		wflt := WsubFinderLinksTerms3{
			_exists: true,
		}

		// scan
		err = q.Scan(&wflt.LinkID, &wflt.TermID, &wflt.Weight)
		if err != nil {
			return nil, err
		}

		res = append(res, &wflt)
	}

	return res, nil
}

// WsubFinderLinksTerms3sByTermIDWeight retrieves a row from 'jlabo.wsub_finder_links_terms3' as a WsubFinderLinksTerms3.
//
// Generated from index 'idx_term_weight'.
func WsubFinderLinksTerms3sByTermIDWeight(db XODB, termID uint, weight float32) ([]*WsubFinderLinksTerms3, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`link_id, term_id, weight ` +
		`FROM jlabo.wsub_finder_links_terms3 ` +
		`WHERE term_id = ? AND weight = ?`

	// run query
	XOLog(sqlstr, termID, weight)
	q, err := db.Query(sqlstr, termID, weight)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*WsubFinderLinksTerms3{}
	for q.Next() {
		wflt := WsubFinderLinksTerms3{
			_exists: true,
		}

		// scan
		err = q.Scan(&wflt.LinkID, &wflt.TermID, &wflt.Weight)
		if err != nil {
			return nil, err
		}

		res = append(res, &wflt)
	}

	return res, nil
}

// WsubFinderLinksTerms3ByTermID retrieves a row from 'jlabo.wsub_finder_links_terms3' as a WsubFinderLinksTerms3.
//
// Generated from index 'wsub_finder_links_terms3_term_id_pkey'.
func WsubFinderLinksTerms3ByTermID(db XODB, termID uint) (*WsubFinderLinksTerms3, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`link_id, term_id, weight ` +
		`FROM jlabo.wsub_finder_links_terms3 ` +
		`WHERE term_id = ?`

	// run query
	XOLog(sqlstr, termID)
	wflt := WsubFinderLinksTerms3{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, termID).Scan(&wflt.LinkID, &wflt.TermID, &wflt.Weight)
	if err != nil {
		return nil, err
	}

	return &wflt, nil
}
